chat/urls.py
# chat/urls.py
from django.urls import path

from . import views

app_name = 'chat'

urlpatterns = [
    path('', views.index, name='index'),
    path('<str:room_name>/', views.room, name='room'),
]

jobs/urls.py
from django.urls import path

from . import views

app_name = 'jobs'

urlpatterns = [
		path('add/', views.createJob, name='job_create'),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('chat/', include('chat.urls')),
    path('jobs/', include('jobs.urls')),
]

posts/urls.py
from django.urls import path
from .views import PostCreateView, PostUpdateView, PostDetailView, PostDeleteView, ajaxSetPostLocation, PostListView, postUserListView, postCreateView, ajaxCreatePost

app_name="posts"

urlpatterns = [
    path('', PostListView.as_view(), name='post_list'),
    path('add/', postCreateView, name='post_add'),
#    path('add/', PostCreateView.as_view(), name='post_add'),
    path('<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('<slug:slug>/', postUserListView, name='post_user_list'),
    path('<int:pk>/update', PostUpdateView.as_view(), name='post_update'),
    path('<int:pk>/delete/', PostDeleteView.as_view(), name='post_delete'),
    path('ajax/location', ajaxSetPostLocation, name='ajax_location'),
    path('ajax/post', ajaxCreatePost, name='ajax_post'),
]

posts/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.conf import settings
from django.urls import reverse

from random import randint

from locations.models import Location
from .utils import upload_image_path


class Post(models.Model):
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='posts')
    title = models.CharField(max_length=50)
    content = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    timestamp = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)
    featured = models.BooleanField(default=False)
    location = models.ForeignKey(Location, on_delete=models.CASCADE, related_name='posts')

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('posts:post_detail', kwargs={'pk': self.pk})

class Image(models.Model):
    title = models.CharField(max_length=60)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to=upload_image_path)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.post.title + 'image'

    def save(self, *args, **kwargs):
        from PIL import Image
        from io import BytesIO
        from django.core.files.uploadedfile import InMemoryUploadedFile
        from sys import getsizeof

        image = self.image
        if not image:
            image = None
            return image

        size = (850,850)

        im = Image.open(image)
        output = BytesIO()
        im.resize(size, Image.ANTIALIAS)
        try:
            im.save(output, format='JPEG', quality=100)
            output.seek(0)
            image = InMemoryUploadedFile(output,'ImageField', "%s.jpg" %image.name.split('.')[0], 'image/jpeg', getsizeof(output), None)
        except:
            im.save(output, format='PNG', quality=100)
            output.seek(0)
            image = InMemoryUploadedFile(output,'ImageField', "%s.png" %image.name.split('.')[0], 'image/png', getsizeof(output), None)
        self.image = image
        super().save(*args, **kwargs)

posts/forms.py
from django import forms
from .models import Post, Image
from django.forms import BaseFormSet

class PostCreateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title','content', 'price']

class ImageForm(forms.ModelForm):
    image = forms.ImageField(required=False)

    class Meta:
        model = Image
        fields = ('image',)

        def clean_image(self, *args, **kwargs):
            from PIL import Image
            from io import BytesIO
            from django.core.files.uploadedfile import InMemoryUploadedFile
            from sys import getsizeof

            image = form.cleaned_data["image"]
            if not image:
                image = None
                return image

            size = (850,850)

            im = Image.open(image)
            output = BytesIO()
            im.resize(size, Image.ANTIALIAS)
            try:
                im.save(output, format='JPEG', quality=100)
                output.seek(0)
                image = InMemoryUploadedFile(output,'ImageField', "%s.jpg" %image.name.split('.')[0], 'image/jpeg', getsizeof(output), None)
            except:
                im.save(output, format='PNG', quality=100)
                output.seek(0)
                image = InMemoryUploadedFile(output,'ImageField', "%s.png" %image.name.split('.')[0], 'image/png', getsizeof(output), None)

            form.cleaned_data['image'] = image
            form.instance.image = image
            return image

class BaseImageFormset(BaseFormSet):
    def clean(self):
        if any(self.errors):
            return
        super().clean()
        for form in self.forms:
            from PIL import Image
            from io import BytesIO
            from django.core.files.uploadedfile import InMemoryUploadedFile
            from sys import getsizeof

            try:
                image = form.cleaned_data["image"]
            except:
                break
            if not image:
                image = None
                return image

            size = (850,850)

            im = Image.open(image)
            output = BytesIO()
            im.resize(size, Image.ANTIALIAS)
            try:
                im.save(output, format='JPEG', quality=100)
                output.seek(0)
                image = InMemoryUploadedFile(output,'ImageField', "%s.jpg" %image.name.split('.')[0], 'image/jpeg', getsizeof(output), None)
            except:
                im.save(output, format='PNG', quality=100)
                output.seek(0)
                image = InMemoryUploadedFile(output,'ImageField', "%s.png" %image.name.split('.')[0], 'image/png', getsizeof(output), None)

            form.cleaned_data['image']= image
            form.instance.image = image

posts/views.py
from django.shortcuts import render, redirect
from django.views.generic import (DetailView, TemplateView, 
                                  UpdateView, DeleteView, 
                                  CreateView, ListView)
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.shortcuts import get_object_or_404
from django.http import Http404
from django.contrib.auth.decorators import login_required

#from allauth.account.models import Profile
from locations.models import Location
from .models import Post, Image
from .forms import PostCreateForm, BaseImageFormset, ImageForm
from django.forms import modelformset_factory, formset_factory
from django.http import HttpResponse
import json
from django.core import serializers


@login_required(login_url='/accounts/login/')
def postCreateView(request):
    ImageFormset = formset_factory(form=ImageForm, formset=BaseImageFormset, extra=3)
    if request.method == 'POST':
        form = PostCreateForm(request.POST)
        formset = ImageFormset(request.POST or None, request.FILES or None)
        if form.is_valid() and formset.is_valid():
            post = form.save(commit=False)
            i = request.POST['Post']
            post.owner = request.user
            post.save()
            i = 1
            for instance in formset:
                try:
                    photo = Image(post=post, image=instance.cleaned_data['image'], title=str(i))
                    photo.save()
                    i = i + 1
                except Exception as e:
                     break
            return redirect('posts:post_list')
    else:
        form = PostCreateForm()
        formset = ImageFormset(Image.objects.none())
        formset = ImageFormset()
        context = {
     	        'form': form,
                'formset': formset,
        }
        return render(request, 'posts/post_form.html', context)

class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'content', 'price']

    def form_valid(self, form):
        form.instance.owner = self.request.user
        form.instance.location = Location.objects.get(pk=self.request.POST.get('location'))
        messages.success(self.request, "Post added.")
        return super().form_valid(form)

class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    fields = ['title', 'content', 'price']
    
    def get_object(self, *args, **kwargs):
        instance = get_object_or_404(Post, owner=self.request.user, pk=self.kwargs['pk'])
        return instance

    def form_valid(self, form):
        messages.success(self.request, "Post updated.")
        return super().form_valid(form)

class PostDetailView(DetailView):
    template_name = "posts/post.html"
    
    def get_object(self, *args, **kwargs):
        try:
            instance = get_object_or_404(Post, pk=self.kwargs['pk'])
        except Post.DoesNotExist:
            raise Http404('Post not found or has been removed.')
        except Post.MultipleObjectsReturned:
            qs = Post.objects.filter(pk=self.kwargs['pk'])
            instance = qs.first()
        except:
           raise Http404("Please contact support.")
        return instance

class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('posts:post_list')

@login_required(login_url='/accounts/login/')
def postUserListView(request, slug):
    template = "posts/post_list.html"
    qs = Post.objects.filter(owner=slug)
    return render(request, template, {'object_list': qs})


class PostListView(ListView):
    model = Post

    def get_queryset(self):
        return Post.objects.filter(active=True)

def ajaxSetPostLocation(request):
    if request.method == 'POST':
        if request.is_ajax():
            l = []
            city = request.POST.get('city', None)
            l.append(city)
            state = request.POST.get('state', None)
            l.append(state)
            country = request.POST.get('country', None)
            l.append(country)
            lng = request.POST.get('lng', None)
            l.append(lng)
            lat = request.POST.get('lat', None)
            l.append(lat)
            city = request.POST.get('city', None)
            state = request.POST.get('state', None)
            country = request.POST.get('country', None)
            lng = request.POST.get('lng', None)
            lat = request.POST.get('lat', None)
            pk = request.POST.get('id', None)

            response_data = {}

            # create of get location
            location, created = Location.objects.get_or_create(city=city, state=state, country=country)

            if created:
                location.latitude = lat
                location.longitude = lng
                location.save()

            if pk != None:
                post = Post.objects.get(pk=pk)
                if not all(v is None for v in l):
                    post.location = location
                post.title = request.POST.get('title')
                post.price = request.POST.get('price')
                post.content = request.POST.get('content')
                post.save()
                url = '/posts/' + str(post.id) + '/'
                response_data['status'] = 'Update Post'
                response_data['url'] = url
                return HttpResponse(
                        json.dumps(response_data),
                        content_type = 'application/json'
                )

            response_data['status'] = 'Create Post'
            response_data['location'] = location.id
            return HttpResponse(
                    json.dumps(response_data),
                    content_type='application/json'
            )


def ajaxCreatePost(request):
    if request.method == 'POST':
        location = request.POST.get('loc')
        success = 'success!'

        form = PostCreateForm(request.POST)
        ImageFormset = formset_factory(form=ImageForm, formset=BaseImageFormset, extra=3)
        if form.is_valid():
            _location = Location.objects.get(pk=location)
            post = form.save(commit=False)
            post.owner = request.user
            post.location = _location
            post.save()

            i = 1
            formset = ImageFormset(request.POST, request.FILES)
            for instance in formset:
                try:
                    photo = Image(post=post, image=instance.cleaned_data['image'], title=str(i))
                    photo.save()
                    i = i + 1
                except Exception as e:
                     break

        if form.is_valid():
            post_location = Location.objects.get(pk=location)
            post = form.save(commit=False)
            post.owner = request.user
            post.location = post_location
            post.save()
            url = '/posts/' + str(post.id) + '/'
            return HttpResponse(
                    json.dumps({'url': url}),
                    content_type='application/json'
            )

        return HttpResponse(
                json.dumps({'status': 'invalid'}),
                content_type='application/json'
        )

templates/posts/js.html
{% extends 'base.html' %}

{% block content %}





{% endblock content %}


{% block extra_js %}

// Submit post on submit
$('#post-form').on('submit', function(event){
    event.preventDefault();
    console.log("form submitted!")  // sanity check
    create_post();
});

{% endblock extra_js %}

templates/posts/post.html
{% extends 'base.html' %}

{% block content %}

<div class='row'>
	<div class='col-lg-6 col-md-6 mx-auto'>
		{% include 'posts/snippets/card.html' with instance=object %}
	</div>

	<div class='col-lg-6 col-md-6 mx-auto'>
       		<div class='col-12'>
         		{{ object.user.profile }}
	                {% if object.user.profile.image %}<img class="d-block img-fluid" src="{{ object.user.profile.image.url }}" alt="#">{% endif %}

		</div>
	</div>
</div>

		<br/>
		{% include 'posts/snippets/map.html' with obj=object %}
	</div>
</div>

{% endblock %}
{% if request.user != object.owner %}
{% block extra_js %}
<script type='text/javascript'>
$(document).ready(function(){

			function getCookie(name) {
		var cookieValue = null;
    		if (document.cookie && document.cookie !== '') {
        		var cookies = document.cookie.split(';');
        		for (var i = 0; i < cookies.length; i++) {
                		var cookie = jQuery.trim(cookies[i]);
            			// Does this cookie string begin with the name we want?
        	    		if (cookie.substring(0, name.length + 1) === (name + '=')) {
	                		cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                			break;
            			}
        		}
    		}
    		return cookieValue;
	}

	var csrftoken = getCookie('csrftoken');

	function csrfSafeMethod(method) {
    		// these HTTP methods do not require CSRF protection
    		return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
	}
	$.ajaxSetup({
    		beforeSend: function(xhr, settings) {
        		if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
            			xhr.setRequestHeader("X-CSRFToken", csrftoken);
        		}
    		}
	});




                        $('.mb').on('click', function(event){
				console.log($('.bid').val());
                                $.ajax({
                                        url : "{% url 'jobs:job_create' %}",
                                        type: 'POST',
                                        data: {bid: $('.bid').val(),
					       post_id: {{object.id}} },
                                });
                        });
        });
</script>

{% endblock %}

{% endif %}

templates/posts/post_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
</form>

{% endblock %}

templates/posts/post_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<form class='form postForm' method='POST' enctype='multipart/form-data'>
	{% csrf_token %}
	{{ form|crispy }}
	{{ formset|crispy}}
        <input type="text" id="txtautocomplete" style="width:200px" placeholder="{{ form.instance.location }}" />
        <button class="primaryAction btn btn-success" type="submit">Submit</button>
</form>

{% endblock content %}

{% block extra_js %}
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD52gtDK6h64U9oRPhszZvDYKobM7ieII0&libraries=places"></script>

<script type='text/javascript'>

	var itemCity = '';
        var itemPc='';
        var itemState = '';
        var itemCountry='';
        var itemAddress= '';
        var itemLat = 0.0;
        var itemLng = 0.0;

	function getCookie(name) {
		var cookieValue = null;
    		if (document.cookie && document.cookie !== '') {
        		var cookies = document.cookie.split(';');
        		for (var i = 0; i < cookies.length; i++) {
                		var cookie = jQuery.trim(cookies[i]);
            			// Does this cookie string begin with the name we want?
        	    		if (cookie.substring(0, name.length + 1) === (name + '=')) {
	                		cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                			break;
            			}
        		}
    		}
    		return cookieValue;
	}

	var csrftoken = getCookie('csrftoken');

	function csrfSafeMethod(method) {
    		// these HTTP methods do not require CSRF protection
    		return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
	}
	$.ajaxSetup({
    		beforeSend: function(xhr, settings) {
        		if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
            			xhr.setRequestHeader("X-CSRFToken", csrftoken);
        		}
    		}
	});


	//AJAX create post function
	function create_post(local, data){
		console.log('inside create post function')
		var f = $('.postForm').serialize() + '&loc=' + local;
	        console.log(f)	


		$.ajax({
			url : "{% url 'posts:ajax_post' %}",
			type: "POST",
			data: data + '&loc=' + local,
			enctype: 'multipart/form-data',			

			success : function(json) {
			//$(location).attr('href', json['url']);
			},
			error : function(xhr, errmsg, err) {
				$('#results').html("<div class='alert-box alert radius' data-alert>Oops! We have encountered an error: "+errmsg+" <a href='#' class='close'>&times;</a></div>")
				console.log(xhr.status + ': ' + xhr.responseText);
			}	
		});
	};



	//AJAX get location function
        function get_location() {
        var data = { 
					{% if form.instance.id %}id: {{form.instance.id}},{% endif %}
					city    : itemCity,
					state   : itemState,
					country :itemCountry,
					lat     : itemLat,
					lng     : itemLng
					};
		var form = $('.postForm').serialize();
		console.log('now inside get_location');
		$.ajax({
			url  : "{% url 'posts:ajax_location' %}",
			type : 'POST',
			data : form + '&' + $.param(data),
			success : function(json) {
				console.log('success call')
				if (json['status'] = 'Update Post') {
					$(location).attr('href', json['url']);
				} 
				if (json['status'] = 'Create Post') {
					local = json['location']
					create_post(local, form);
				}
			},
			error : function(xhr, errmsg, err) {
				$('#results').html("<div class='alert-box alert radius' data-alert>Oops! We have encountered an error: "+errmsg+" <a href='#' class='close'>&times;</a></div>")
				console.log(xhr.status + ': ' + xhr.responseText);
			}
		});
	};



    google.maps.event.addDomListener(window, 'load', intilize);
        function intilize() {
                var autocomplete = new google.maps.places.Autocomplete(document.getElementById('txtautocomplete'));

                        google.maps.event.addListener(autocomplete, 'place_changed', function () {

                                var place = autocomplete.getPlace();
                                var arrAddress = place.address_components;

                                itemLat = place.geometry.location.lat();
                                itemLng = place.geometry.location.lng();                      

                                // iterate through address_component array
                                $.each(arrAddress, function (i, address_component) {

                                    if (address_component.types[0] == "locality"){
                                        itemCity = address_component.long_name;
                                    }

                                    if (address_component.types[0] == "country"){ 
                                        itemCountry = address_component.short_name;
                                    }

                                    if (address_component.types[0] == "administrative_area_level_1"){ 
                                        itemState = address_component.short_name;
                                    }

                                    if (address_component.types[0] == "postal_code"){ 
                                        itemPc = address_component.long_name;
                                    }
                                    //return false; // break the loop   
                                });
		});
        };

	$(document).ready(function(){
		$('form').on('submit', function(event){
			event.preventDefault();
			var form = $('.postForm');
			console.log('form submitted!')
			get_location();
		});
	});
</script>
{% endblock extra_js%}

templates/posts/post_list.html
{% extends 'base.html' %}
<!-- {{ object_list }} -->

{% block content%}
                <div class='row'>
                        {% for object in object_list %}
                                <div class='col-sm-6 col-md-4 col-lg-3 mt-4'>
                                        {% include 'posts/snippets/card.html' with instance=object %}
                                </div>
                                {% if forloop.counter|divisibleby:4 %}
                                </div>
                                        <div class='row'>
                        
                                
                        {% endif %}
                        {% endfor %}
                </div>
{% endblock %}

templates/posts/test.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<form class='form postForm' method='POST' enctype='multipart/form-data'>
	{{ form.non_field_errors }}
	<div class="fieldWrapper">
    		{{ form.title.errors }}
    		<label for="{{ form.subject.id_for_label }}">title:</label>
   		{{ form.title }}
	</div>
        <button class="primaryAction btn btn-success" type="submit">Submit</button>
</form>

{% endblock %}