chat/urls.py
# chat/urls.py
from django.urls import path

from . import views

app_name = 'chat'

urlpatterns = [
    path('', views.index, name='index'),
    path('<str:room_name>/', views.room, name='room'),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('chat/', include('chat.urls')),
    path('jobs/', include('jobs.urls')),
]

posts/urls.py
from django.urls import path
from .views import PostCreateView, PostUpdateView, PostDetailView, PostDeleteView, ajaxSetPostLocation, PostListView, postUserListView, postCreateView, ajaxCreatePost

app_name="posts"

urlpatterns = [
    path('', PostListView.as_view(), name='post_list'),
    path('add/', postCreateView, name='post_add'),
#    path('add/', PostCreateView.as_view(), name='post_add'),
    path('<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('<slug:slug>/', postUserListView, name='post_user_list'),
    path('<int:pk>/update', PostUpdateView.as_view(), name='post_update'),
    path('<int:pk>/delete/', PostDeleteView.as_view(), name='post_delete'),
    path('ajax/location', ajaxSetPostLocation, name='ajax_location'),
    path('ajax/post', ajaxCreatePost, name='ajax_post'),
]

posts/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.conf import settings
from django.urls import reverse

from random import randint

from locations.models import Location
from .utils import upload_image_path


class Post(models.Model):
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='posts')
    title = models.CharField(max_length=50)
    content = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    timestamp = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)
    featured = models.BooleanField(default=False)
    location = models.ForeignKey(Location, on_delete=models.CASCADE, related_name='posts')

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('posts:post_detail', kwargs={'pk': self.pk})

class Image(models.Model):
    title = models.CharField(max_length=60)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to=upload_image_path)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.post.title + 'image'

    def save(self, *args, **kwargs):
        from PIL import Image
        from io import BytesIO
        from django.core.files.uploadedfile import InMemoryUploadedFile
        from sys import getsizeof

        image = self.image
        if not image:
            image = None
            return image

        size = (850,850)

        im = Image.open(image)
        output = BytesIO()
        im.resize(size, Image.ANTIALIAS)
        try:
            im.save(output, format='JPEG', quality=100)
            output.seek(0)
            image = InMemoryUploadedFile(output,'ImageField', "%s.jpg" %image.name.split('.')[0], 'image/jpeg', getsizeof(output), None)
        except:
            im.save(output, format='PNG', quality=100)
            output.seek(0)
            image = InMemoryUploadedFile(output,'ImageField', "%s.png" %image.name.split('.')[0], 'image/png', getsizeof(output), None)
        self.image = image
        super().save(*args, **kwargs)

posts/forms.py
from django import forms
from .models import Post, Image
from django.forms import BaseFormSet

class PostCreateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title','content', 'price']

class ImageForm(forms.ModelForm):
    image = forms.ImageField(required=False)

    class Meta:
        model = Image
        fields = ('image',)

        def clean_image(self, *args, **kwargs):
            from PIL import Image
            from io import BytesIO
            from django.core.files.uploadedfile import InMemoryUploadedFile
            from sys import getsizeof

            image = form.cleaned_data["image"]
            if not image:
                image = None
                return image

            size = (850,850)

            im = Image.open(image)
            output = BytesIO()
            im.resize(size, Image.ANTIALIAS)
            try:
                im.save(output, format='JPEG', quality=100)
                output.seek(0)
                image = InMemoryUploadedFile(output,'ImageField', "%s.jpg" %image.name.split('.')[0], 'image/jpeg', getsizeof(output), None)
            except:
                im.save(output, format='PNG', quality=100)
                output.seek(0)
                image = InMemoryUploadedFile(output,'ImageField', "%s.png" %image.name.split('.')[0], 'image/png', getsizeof(output), None)

            form.cleaned_data['image'] = image
            form.instance.image = image
            return image

class BaseImageFormset(BaseFormSet):
    def clean(self):
        if any(self.errors):
            return
        super().clean()
        for form in self.forms:
            from PIL import Image
            from io import BytesIO
            from django.core.files.uploadedfile import InMemoryUploadedFile
            from sys import getsizeof

            try:
                image = form.cleaned_data["image"]
            except:
                break
            if not image:
                image = None
                return image

            size = (850,850)

            im = Image.open(image)
            output = BytesIO()
            im.resize(size, Image.ANTIALIAS)
            try:
                im.save(output, format='JPEG', quality=100)
                output.seek(0)
                image = InMemoryUploadedFile(output,'ImageField', "%s.jpg" %image.name.split('.')[0], 'image/jpeg', getsizeof(output), None)
            except:
                im.save(output, format='PNG', quality=100)
                output.seek(0)
                image = InMemoryUploadedFile(output,'ImageField', "%s.png" %image.name.split('.')[0], 'image/png', getsizeof(output), None)

            form.cleaned_data['image']= image
            form.instance.image = image

posts/views.py
from django.shortcuts import render, redirect
from django.views.generic import (DetailView, TemplateView, 
                                  UpdateView, DeleteView, 
                                  CreateView, ListView)
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.shortcuts import get_object_or_404
from django.http import Http404
from django.contrib.auth.decorators import login_required

#from allauth.account.models import Profile
from locations.models import Location
from .models import Post, Image
from .forms import PostCreateForm, BaseImageFormset, ImageForm
from django.forms import modelformset_factory, formset_factory
from django.http import HttpResponse
import json
from django.core import serializers


@login_required(login_url='/accounts/login/')
def postCreateView(request):
    ImageFormset = formset_factory(form=ImageForm, formset=BaseImageFormset, extra=3)
    if request.method == 'POST':
        form = PostCreateForm(request.POST)
        formset = ImageFormset(request.POST or None, request.FILES or None)
        if form.is_valid() and formset.is_valid():
            post = form.save(commit=False)
            i = request.POST['Post']
            post.owner = request.user
            post.save()
            i = 1
            for instance in formset:
                try:
                    photo = Image(post=post, image=instance.cleaned_data['image'], title=str(i))
                    photo.save()
                    i = i + 1
                except Exception as e:
                     break
            return redirect('posts:post_list')
    else:
        form = PostCreateForm()
        formset = ImageFormset(Image.objects.none())
        formset = ImageFormset()
        context = {
     	        'form': form,
                'formset': formset,
        }
        return render(request, 'posts/post_form.html', context)

class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'content', 'price']

    def form_valid(self, form):
        form.instance.owner = self.request.user
        form.instance.location = Location.objects.get(pk=self.request.POST.get('location'))
        messages.success(self.request, "Post added.")
        return super().form_valid(form)

class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    fields = ['title', 'content', 'price']
    
    def get_object(self, *args, **kwargs):
        instance = get_object_or_404(Post, owner=self.request.user, pk=self.kwargs['pk'])
        return instance

    def form_valid(self, form):
        messages.success(self.request, "Post updated.")
        return super().form_valid(form)

class PostDetailView(DetailView):
    template_name = "posts/post.html"
    
    def get_object(self, *args, **kwargs):
        try:
            instance = get_object_or_404(Post, pk=self.kwargs['pk'])
        except Post.DoesNotExist:
            raise Http404('Post not found or has been removed.')
        except Post.MultipleObjectsReturned:
            qs = Post.objects.filter(pk=self.kwargs['pk'])
            instance = qs.first()
        except:
           raise Http404("Please contact support.")
        return instance

class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('posts:post_list')

@login_required(login_url='/accounts/login/')
def postUserListView(request, slug):
    template = "posts/post_list.html"
    qs = Post.objects.filter(owner=slug)
    return render(request, template, {'object_list': qs})


class PostListView(ListView):
    model = Post

    def get_queryset(self):
        return Post.objects.filter(active=True)

def ajaxSetPostLocation(request):
    if request.method == 'POST':
        if request.is_ajax():
            l = []
            city = request.POST.get('city', None)
            l.append(city)
            state = request.POST.get('state', None)
            l.append(state)
            country = request.POST.get('country', None)
            l.append(country)
            lng = request.POST.get('lng', None)
            l.append(lng)
            lat = request.POST.get('lat', None)
            l.append(lat)
            city = request.POST.get('city', None)
            state = request.POST.get('state', None)
            country = request.POST.get('country', None)
            lng = request.POST.get('lng', None)
            lat = request.POST.get('lat', None)
            pk = request.POST.get('id', None)

            response_data = {}

            # create of get location
            location, created = Location.objects.get_or_create(city=city, state=state, country=country)

            if created:
                location.latitude = lat
                location.longitude = lng
                location.save()

            if pk != None:
                post = Post.objects.get(pk=pk)
                if not all(v is None for v in l):
                    post.location = location
                post.title = request.POST.get('title')
                post.price = request.POST.get('price')
                post.content = request.POST.get('content')
                post.save()
                url = '/posts/' + str(post.id) + '/'
                response_data['status'] = 'Update Post'
                response_data['url'] = url
                return HttpResponse(
                        json.dumps(response_data),
                        content_type = 'application/json'
                )

            response_data['status'] = 'Create Post'
            response_data['location'] = location.id
            return HttpResponse(
                    json.dumps(response_data),
                    content_type='application/json'
            )


def ajaxCreatePost(request):
    if request.method == 'POST':
        location = request.POST.get('loc')
        success = 'success!'

        form = PostCreateForm(request.POST)
        ImageFormset = formset_factory(form=ImageForm, formset=BaseImageFormset, extra=3)
        if form.is_valid():
            _location = Location.objects.get(pk=location)
            post = form.save(commit=False)
            post.owner = request.user
            post.location = _location
            post.save()

            i = 1
            formset = ImageFormset(request.POST, request.FILES)
            for instance in formset:
                try:
                    photo = Image(post=post, image=instance.cleaned_data['image'], title=str(i))
                    photo.save()
                    i = i + 1
                except Exception as e:
                     break

        if form.is_valid():
            post_location = Location.objects.get(pk=location)
            post = form.save(commit=False)
            post.owner = request.user
            post.location = post_location
            post.save()
            url = '/posts/' + str(post.id) + '/'
            return HttpResponse(
                    json.dumps({'url': url}),
                    content_type='application/json'
            )

        return HttpResponse(
                json.dumps({'status': 'invalid'}),
                content_type='application/json'
        )

templates/posts/snippets/card.html
{% url 'posts:post_detail' pk=instance.id as post_detail_url %}

<div class="card border border-dark">

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner" role="listbox">
    {% for image in instance.images.all|slice:"3" %}
      {% if forloop.first %}
        <div class="carousel-item active">
      {% else %}
        <div class="carousel-item">
      {% endif %}
          <img class="d-block img-fluid" src="{{ image.image.url }}" alt={% if image.title %}"{{image.title}}"{% endif %}>
        </div>
    {% endfor %}
   <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
</div>
    <div class="card-body">
      <h5 class="card-title">{{ instance.title }}</h5>
      <h5>{{ instance.price }}</h5>
      <p class="card-text">{% if request.path == post_detail_url %}{{ instance.content }}{% else %}{{ instance.content|truncatewords:12 }}{% endif %}</p>
    </div>
    <div class="card-footer">
      <small class="text-muted">{{ instance.created|timesince }} ago</small>
      <small class="pull-right">{{ instance.location }}</small>
      {% if request.user == instance.owner and request.path == post_detail_url %}
      <a href="{% url 'posts:post_update' pk=instance.id %}" class="btn btn-warning">Update</a>
      <a href="{% url 'posts:post_delete' pk=instance.id %}" class="btn btn-danger">Delete</a></small>
      {% elif request.user != instance.owner and request.path == post_detail_url %}

	<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
  Make Bid
</button>  


      {% elif request.path != post_detail_url %}
      <a href="{% url 'posts:post_detail' pk=instance.id %}" class="btn btn-info btn-block">view</a>
      {% endif %}
    </div>
</div>


<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h2 class="modal-title mx-auto" id="exampleModalLabel"><strong>Enter your offer</strong></h2>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
	<h5><center>{{ instance.title }}</center></h5>
      <div class="modal-body mx-auto">
	<form class='form formBid' action='{% url 'posts:post_add' %}' method='POST'>
		<div class='form-group'>
			<input class='bid form-control' type='text' name='bid' value='{{ instance.price }}'>
		</div>
	</form>
      </div>
      <div class="modal-footer">
	<hr>
        <button type="button" class="mb btn btn-block btn-primary">Send Offer</button>
      </div>
    </div>
  </div>
</div>

templates/posts/snippets/map.html
<style>
      /* Always set the map height explicitly to define the size of the div
       * element that contains the map. */
      #map {
        height: 50%;
      }
</style> 




<div class="card border border-dark">
  <div class='card-body'>
    <div id="map"></div>
  </div>
</div>

<script>
      var size = {lat: {{ obj.location.latitude }}, lng: {{ obj.location.longitude }}}
      function initMap() {
        // Create the map.
        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 11,
          center: size,
          disableDefaultUI: true,
        });

          var cityCircle = new google.maps.Circle({
            strokeColor: '#424242',
            strokeOpacity: 0.8,
            strokeWeight: 2,
            fillColor: '#424242',
            fillOpacity: 0.35,
            map: map,
            center: size,
            radius: 2500
          });
      }
    </script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD52gtDK6h64U9oRPhszZvDYKobM7ieII0&callback=initMap">
    </script>