chat/urls.py
# chat/urls.py
from django.urls import path

from . import views

app_name = 'chat'

urlpatterns = [
    path('', views.index, name='index'),
    path('<str:room_name>/', views.room, name='room'),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('chat/', include('chat.urls')),
    path('jobs/', include('jobs.urls')),
]

posts/urls.py
from django.urls import path
from .views import PostCreateView, PostUpdateView, PostDetailView, PostDeleteView, ajaxSetPostLocation, PostListView, postUserListView, postCreateView, ajaxCreatePost

app_name="posts"

urlpatterns = [
    path('', PostListView.as_view(), name='post_list'),
    path('add/', postCreateView, name='post_add'),
#    path('add/', PostCreateView.as_view(), name='post_add'),
    path('<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('<slug:slug>/', postUserListView, name='post_user_list'),
    path('<int:pk>/update', PostUpdateView.as_view(), name='post_update'),
    path('<int:pk>/delete/', PostDeleteView.as_view(), name='post_delete'),
    path('ajax/location', ajaxSetPostLocation, name='ajax_location'),
    path('ajax/post', ajaxCreatePost, name='ajax_post'),
]

templates/base/css.html
{% load static %}

<!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <link rel='stylesheet' href='{% static "css/main.css" %}'>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

templates/base/js.html
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>

templates/base/nav.html
<nav class="navbar navbar-expand-lg navbar-dark nav-custom-bg mb-3">
<div class='container'>
  <a class="navbar-brand" href="#"><strong>TheYardApp.com</strong><a/>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'posts:post_list' %}"><span class="myicons-home3"></span></a>
        </li>	

      <!-- <div class="input-group input-group-sm form-group">
 <form class="navbar-form navbar-left" role="search">
  <span class="input-group-addon" id="sizing-addon3">@</span>
  <input type="text" class="form-control" placeholder="Username" aria-describedby="sizing-addon3">
<button type="submit" class="btn btn-default">Submit</button>
</form>
</div>-->


        {% if request.user.is_authenticated %}
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Post</a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{% url 'posts:post_add' %}">Add Post</a>
        </div>
      </li>
 
      </ul>
      <ul class="navbar-nav justify-content-end">
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span class="myicons-user"></span> {{ request.user.username|title }}</a>
      </li>
        <li>
        </li>
      </ul>
      {% endif %} 
    </div>
  </div>
</nav>