chat/urls.py
# chat/urls.py
from django.urls import path

from . import views

app_name = 'chat'

urlpatterns = [
    path('', views.index, name='index'),
    path('<str:room_name>/', views.room, name='room'),
]

locations/urls.py
from django.urls import path
from .views import get_location, Example

app_name='locations'

urlpatterns = [
    path('ajax/get_location', get_location, name='ajax_get_location'),
    path('home', Example.as_view()),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('chat/', include('chat.urls')),
    path('jobs/', include('jobs.urls')),
]

locations/models.py
from django.db import models

class LocationManager(models.Manager):

    def create_new(self, data):
        location = self.model()
        if data is not None:
            city = data['city']
            state = data['region']
            if not Location.objects.filter(city=city, state=state).exists():
                location.city = city
                location.state = state
                location.country = data['country_code']
                location.latitude = data['latitude']
                location.longitude = data['longitude']
                location.save()
                return location
            else:
                return Location.objects.get(city=city, state=state)


class Location(models.Model):
    city        = models.CharField(max_length=120, null=True, blank=True)
    state       = models.CharField(max_length=2, null=True, blank=True)
    country     = models.CharField(max_length=20)
    latitude    = models.FloatField(null=True, blank=True)
    longitude   = models.FloatField(null=True, blank=True)

    objects = LocationManager()

    def __str__(self):
        return '{}, {}'.format(self.city, self.state)

locations/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.views.generic import TemplateView

from .models import Location

def get_location(request):
    city = request.POST.get('city', None)
    state = request.POST.get('state', None)
    country = request.POST.get('country', None)
    lng = request.POST.get('longitude', None)
    lat = request.POST.get('latitude', None)

    location, created = Location.objects.get_or_create(city=city, state=state, country=country)
    success = 'Location found'
    
    if created:
        location.latitude = lat
        location.longitude = lng
        location.save()
        success = 'Location added.'

    data = {
        'success': success
    }

    return JsonResponse(data)

class Example(TemplateView):
    template_name="locations/local.html"

    def GET(self, request):
        return render(request, self.template_name)

templates/locations/local.html
{% extends 'base.html' %}

{% block content %}

<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD52gtDK6h64U9oRPhszZvDYKobM7ieII0&libraries=places"></script>

<script type="text/javascript">

	var itemCity = '';
	var itemPc='';
	var itemState = '';
	var itemCountry='';
	var itemAddress= '';
	var itemLat = 0.0;
	var itemLng = 0.0;

	google.maps.event.addDomListener(window, 'load', intilize);
	function intilize() {
		var autocomplete = new google.maps.places.Autocomplete(document.getElementById('txtautocomplete'));

			google.maps.event.addListener(autocomplete, 'place_changed', function () {

				$("button").click(function(e) {
                                            e.preventDefault();
				var place = autocomplete.getPlace();
				var arrAddress = place.address_components;

				itemLat = place.geometry.location.lat();
				itemLng = place.geometry.location.lng();				

				// iterate through address_component array
				$.each(arrAddress, function (i, address_component) {

				    if (address_component.types[0] == "locality"){
				        console.log("city:"+address_component.long_name);
				        itemCity = address_component.long_name;
				    }

				    if (address_component.types[0] == "country"){ 
				        console.log("country:"+address_component.short_name); 
				        itemCountry = address_component.short_name;
				    }

				    if (address_component.types[0] == "administrative_area_level_1"){ 
				        console.log("state:"+address_component.short_name); 
				        itemState = address_component.short_name;
				    }

				    if (address_component.types[0] == "postal_code"){ 
				        console.log("pc:"+address_component.long_name);  
				        itemPc = address_component.long_name;
				    }
				    //return false; // break the loop   
				});


				$(document).ready(function(){
					var csrftoken = Cookies.get('csrftoken');
					function csrfSafeMethod(method) {
    // these HTTP methods do not require CSRF protection
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
}
					$.ajaxSetup({
   						 beforeSend: function(xhr, settings) {
					        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
					            xhr.setRequestHeader("X-CSRFToken", csrftoken);
        					}
    					  }
					});
					    $.ajax ({
					      url: "{% url 'locations:ajax_get_location' %}",
					      type: "POST",
					      data: {city: itemCity,
				              state: itemState,
				              country: itemCountry,
				              latitude: itemLat,
				              longitude: itemLng},
				              dataType: "json",
					    });
				})
				
			});
		});
	};
</script>

<span>Location:</span><input type="text" id="txtautocomplete" style="width:200px" placeholder="Enter the address" />
<button class="primaryAction btn btn-success" type="submit">Submit</button>

<br /><br />
<label id="lblresult"></label>

{% endblock %}